name: APS.NET-Core

env:
  DOTNET_VERSION : 5.0.x
  SOLUTION_NAME: TicketManagement.sln
  TEST_PROJECT_PATH: test/TicketManagement.UnitTests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build_and_run_tests:
    runs-on: windows-latest

    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Set up dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore packages
      run: nuget restore ${{ env.SOLUTION_NAME }} /v:minimal

    - name: Build project
      run: msbuild ${{ env.SOLUTION_NAME }} /t:Rebuild /p:RestorePackages="True" /p:Configuration="Release" /v:minimal /p:DebugSymbols="False" /p:DebugType="None"

    - name: Run unit tests
      run: dotnet test ${{ env.TEST_PROJECT_PATH }} --no-build --no-restore -p:Configuration=Release
